### ISSUE TITLE
Show which pakages are multi-theme packages

### ISSUE THREAD

**Issue by ema2159** [freesteph/peach-melpa.org#11]
Some themes like Doom or Kaolin are are multi themes, it should be really nice if the index shown which packages are like this

**Comment by freesteph** [comment]
Good point. It should be an easy one, I'll try and add it soon (currently in a middle of a redesign). I'll keep you posted.

**Comment by freesteph** [comment]
The new PeachMelpa effectively shows a badge. It might get flashier in the future but I think it does the trick for now.

**Comment by ema2159** [comment]
Perfect!
