### ISSUE TITLE
URL query parameter page = 13 returns HTTP 500

### ISSUE THREAD

**Issue by thegoofist** [freesteph/peach-melpa.org#12]
Hello! I love Peach Melpa and have been wasting too too much time browsing themes over the last few days. Thanks for making it!

When I browse to https://peach-melpa.org/themes?page=13 I am met with an error page that reads "We're sorry, but something went wrong" and the HTTP reply status is 500.

It only happens when `page=13`, pages 14 and 12 both work fine.

**Comment by freesteph** [comment]
Hey! Thanks, I'm glad you like it.

I have heard about this error before but was on holiday and didn't had the chance to investigate properly, will do soon.

**Comment by thegoofist** [comment]
I thought it might be a joke: Unlucky Number 13!

**Comment by freesteph** [comment]
Ah! I was born on a Friday 13th so I couldn't possibly let that happen. Turns out it was a rogue theme (`punpun-theme`) that  tricked the Rails app over, not sure how it happened but it's cleared and page 13 now loads. Thanks for the report!
