### ISSUE TITLE
Some themes missing

### ISSUE THREAD

**Issue by purcell** [freesteph/peach-melpa.org#18]
Hey, self-interested issue coming right up... I noticed that `color-theme-sanityinc-tomorrow` and `color-theme-sanityinc-solarized` are not listed in peach-melpa. The former (a set of 5 themes) is the fifth most popular theme on MELPA. Both packages are somewhat obtusely named, since they contain both conventionally-named `*-theme.el` files *and* machinery to make those work with the old `color-theme` package. Not sure how easy it is to add these, but it's probably a matter of changing a package name regexp somewhere?

**Comment by freesteph** [comment]
https://peach-melpa.org/themes/color-theme-sanityinc-tomorrow/variants/sanityinc-tomorrow-blue 

😎

**Comment by purcell** [comment]
Yay, great, thank you!
