### ISSUE TITLE
No variants for "tron-legacy-theme"

### ISSUE THREAD

**Issue by ianpan870102** [freesteph/peach-melpa.org#23]
Last week the theme is still included. However, for some reason tron-legacy is not there anymore today...

**Comment by freesteph** [comment]
Hi Ian,

PeachMelpa is going through a bit of change at the moment, and by that I mean it's fairly broken. I'm hopping to resolve these issues in the next week, please bear with me.

**Comment by ianpan870102** [comment]
Hi Stephane, I see. No problem, I'll wait in the meanwhile. Let me know if you want this issue closed for now.

**Comment by ianpan870102** [comment]
Seems like the issue is fixed. Closing issue!
